# Generated by Django 4.1 on 2022-08-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tag',
            new_name='tyag',
        ),
    ]
