# Generated by Django 4.1 on 2022-08-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_tag_tyag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tyag',
            new_name='tag',
        ),
    ]
