# Generated by Django 4.1 on 2022-08-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_tyag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Tag',
            field=models.ManyToManyField(to='accounts.tag'),
        ),
    ]
